spring.datasource.url=jdbc:sqlserver://localhost;databaseName=VAGAS;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=SA
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.mvc.pathmatch.matching-strategy=ant_path_matcher